const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
  CHANGE_LANGUAGE_APP: "CHANGE_LANGUAGE_APP",

  //user
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  USER_ADD_SUCCESS: "USER_ADD_SUCCESS",
  USER_INFO_SUCCESS: "USER_INFO_SUCCESS",

  //modal
  SHOW_MODAL: "SHOW_MODAL",
  HIDE_MODAL: "HIDE_MODAL",
  CHANGE_MODAL_TITLE: "CHANGE_MODAL_TITLE",
  EDITING_MODAL: "EDITING_MODAL",

  //admin
  ADMIN_LOGIN_SUCCESS: "ADMIN_LOGIN_SUCCESS",
  ADMIN_LOGIN_FAIL: "ADMIN_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",
  ADMIN_CREATE_USER_SUCCESS: "ADMIN_CREATE_USER_SUCCESS",
  ADMIN_CREATE_USER_FAILED: "ADMIN_CREATE_USER_FAILED",
  FETCH_ALL_USERS_SUCCESS: "FETCH_ALL_USERS_SUCCESS",
  FETCH_ALL_USERS_FAILED: "FETCH_ALL_USERS_FAILED",
  DELETE_USERS_SUCCESS: "DELETE_USERS_SUCCESS",
  DELETE_USERS_FAILED: "DELETE_USERS_FAILED",
  EDIT_USERS_SUCCESS: "EDIT_USERS_SUCCESS",
  EDIT_USERS_FAILED: "EDIT_USERS_FAILED",
  FETCH_TOP_DOCTORS_SUCCESS: "FETCH_TOP_DOCTORS_SUCCESS",
  FETCH_TOP_DOCTORS_FAILED: "FETCH_TOP_DOCTORS_FAILED",
  DOCTOR_DETAIL_SUCCESS: "DOCTOR_DETAIL_SUCCESS",
  DOCTOR_DETAIL_FAILED: "DOCTOR_DETAIL_FAILED",
  DOCTOR_MARKDOWN_SUCCESS: "DOCTOR_MARKDOWN_SUCCESS",
  DOCTOR_MARKDOWN_FAILED: "DOCTOR_MARKDOWN_FAILED",
  FETCH_REQUIRED_DOCTOR_INFO_SUCCESS: "FETCH_REQUIRED_DOCTOR_INFO_SUCCESS",
  FETCH_REQUIRED_DOCTOR_INFO_FAILED: "FETCH_REQUIRED_DOCTOR_INFO_FAILED",
  FETCH_ALLCODE_TIME_SUCCESS: "FETCH_ALLCODE_TIME_SUCCESS",
  FETCH_ALLCODE_TIME_FAILED: "FETCH_ALLCODE_TIME_FAILED",
  FETCH_SCHEDULE_TIME_DOCTOR_SUCCESS: "FETCH_SCHEDULE_TIME_DOCTOR_SUCCESS",
  FETCH_SCHEDULE_TIME_DOCTOR_FAILED: "FETCH_SCHEDULE_TIME_DOCTOR_FAILED",
  CLEAR_SCHEDULE_TIME_DOCTOR: "CLEAR_SCHEDULE_TIME_DOCTOR",
  FETCH_ALLCODE_GENDER_SUCCESS: "FETCH_ALLCODE_GENDER_SUCCESS",
  FETCH_ALLCODE_GENDER_FAILED: "FETCH_ALLCODE_GENDER_FAILED",
  CLEAR_BOOKING_INFO: "CLEAR_BOOKING_INFO",
});

export default actionTypes;
